---

- name: validate inputs
  include_tasks: validate.yml

- name: docker compose definition
  debug:
    msg: "{{ definition }}"

- name: "docker compose: {{ state }}"
  community.general.docker_compose:
    project_name: "{{ project_name }}"
    definition: "{{ definition }}"
    state: "{{ state }}"
    restarted: "{{ restarted }}"
    recreate: always
    debug: yes

- name: state=present
  include_tasks: present.yml
  when: state == 'present'

- name: state=absent
  include_tasks: absent.yml
  when: state == 'absent'
