# Copyright (c) 2021, Solace Corporation, Ricardo Gomez-Ulmke, <ricardo.gomez-ulmke@solace.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
---

- set_fact:
    rc: 0
  register: solace_broker_service_result
- set_fact:
    solace_broker_service_result:
      rc: 0

- name: validate inputs
  include_tasks: validate.yml

- name: "call docker compose"
  block:
  - name: "docker compose: {{ combined_docker_compose_settings.project_name }}:{{ combined_docker_compose_settings.state }}"
    community.general.docker_compose: "{{ combined_docker_compose_settings }}"
    register: docker_compose_result
  rescue:
  - set_fact:
      solace_broker_service_result:
        rc: 1
        msg:
          community:
            general:
              docker_compose:
                result: "{{ docker_compose_result }}"
- fail:
    msg: "{{ solace_broker_service_result }}"
  when: solace_broker_service_result.rc != 0

- name: state=present
  include_tasks: present.yml
  when: combined_docker_compose_settings.state == 'present'

- name: state=absent
  include_tasks: absent.yml
  when: combined_docker_compose_settings.state == 'absent'
