# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke, <ricardo.gomez-ulmke@solace.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
---
# generate
- set_fact:
    combined_generate: "{{ default_generate | combine(generate, recursive=true) if generate is defined else default_generate }}"
# docker_compose_settings
- fail:
    msg: "arg 'docker_compose_settings.project_name' - must not be empty"
  when: docker_compose_settings.project_name == args.__null__
- set_fact:
    combined_docker_compose_settings: "{{ default_docker_compose_settings | combine(docker_compose_settings, recursive=true) if docker_compose_settings is defined else default_docker_compose_settings }}"
