# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke, <ricardo.gomez-ulmke@solace.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint


# Upstream container - just to populate the inventory
provisioner:
  inventory:
    hosts:
      all:
        localhost:
          ansible_connection: local
