---

- name: validate inputs
  include_tasks: validate.yml

- name: docker compose
  community.general.docker_compose:
    project_name: "{{ project_name }}"
    definition: "{{ definition }}"
    state: "{{ state }}"
    restarted: "{{ restarted }}"

- name: state=present
  include_tasks: present.yml
  when: state == 'present'

- name: state=absent
  include_tasks: absent.yml
  when: state == 'absent'
