-
  name: create broker service
  hosts: all
  tasks:
  - name: set docker compose yaml file
    set_fact:
      broker_docker_compose_file: "{path}/docker_compose_file.yml"

  - name: create broker service with docker compose file
    include_role:
      name: solace.pubsub_plus.solace_broker_service
    vars:
      docker_compose_settings:
        project_name: my-docker-project-name
        state: present
        definition: "{{ lookup('file', broker_docker_compose_file) | from_yaml }}"
