# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke, <ricardo.gomez-ulmke@solace.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

name: integration test runner
on:
  # for testing
  workflow_dispatch:

  push:
      
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 1 * * *'

env:

  DEBUG_FLAG: ${{ true }}

  TEST_SOLACE_CLOUD_API_TOKEN_ALL_PERMISSIONS: ${{ secrets.SOLACE_CLOUD_API_TOKEN_ALL_PERMISSIONS }}
  TEST_SOLACE_CLOUD_API_TOKEN_RESTRICTED_PERMISSIONS: ${{ secrets.SOLACE_CLOUD_API_TOKEN_RESTRICTED_PERMISSIONS }}
  TEST_ANSIBLE_SOLACE_COLLECTION_DIR: "src/ansible_collections/solace/pubsub_plus"

jobs:
  integration:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [ '3.6', '3.8', '3.9' ]
        python-version: [ '3.6' ]

    steps:

      - name: Print test env
        if: env.DEBUG_FLAG == 'true'
        run: |
          env | grep TEST

      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print Python Version
        if: env.DEBUG_FLAG == 'true'
        run: |
          python -V

      - name: Install ansible and collection dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install -r requirements.txt
          pip install docker-compose

      - name: test
        run: |
          ls -la ${TEST_ANSIBLE_SOLACE_COLLECTION_DIR}


###
# The End.
