# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke, <ricardo.gomez-ulmke@solace.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

name: integration test runner
on:
  # for testing
  workflow_dispatch:

  push:

  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 1 * * *'

env:

  DEBUG_FLAG: ${{ true }}

  # TEST_SOLACE_CLOUD_API_TOKEN_ALL_PERMISSIONS: ${{ secrets.SOLACE_CLOUD_API_TOKEN_ALL_PERMISSIONS }}
  # TEST_SOLACE_CLOUD_API_TOKEN_RESTRICTED_PERMISSIONS: ${{ secrets.SOLACE_CLOUD_API_TOKEN_RESTRICTED_PERMISSIONS }}
  TEST_ANSIBLE_SOLACE_COLLECTION_DIR: "src/ansible_collections/solace/pubsub_plus"
  TEST_TEST_RUNNER_LOG_DIR: "./logs"
  TEST_TEST_RUNNER_SCRIPT: "test-runner/run.wf.sh"
  TEST_TEST_RUNNER_LOGS_NAME: logs
  TEST_RUNNER_LOGS_DIR: logs

jobs:
  integration:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [ '3.6', '3.8', '3.9' ]
        python-version: [ '3.6' ]

    steps:

      - name: Print test env
        if: env.DEBUG_FLAG == 'true'
        run: |
          env | grep TEST

      - name: Print github env before checkout
        if: env.DEBUG_FLAG == 'true'
        run: |
          pwd
          # echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "GITHUB_REF=$GITHUB_REF"

      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print Python Version
        if: env.DEBUG_FLAG == 'true'
        run: |
          python -V

      - name: Install ansible and collection dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install -r requirements.txt
          pip install docker-compose

      - name: Test Installation
        if: env.DEBUG_FLAG == 'true'
        run: |
          pip show ansible
          ansible --version
          ansible-galaxy --version
          pip show xmltodict
          ls -la ${TEST_ANSIBLE_SOLACE_COLLECTION_DIR}

      - name: Build and install collection
        run: |
          cd ${TEST_ANSIBLE_SOLACE_COLLECTION_DIR}
          ansible-galaxy collection build .
          ansible-galaxy collection install *.gz

      - name: Test Collection Installation
        if: env.DEBUG_FLAG == 'true'
        run: |
          pwd
          ls -la
          ansible-galaxy collection list -vvv solace.pubsub_plus

      - name: Run Tests
        run: |
          export ANSIBLE_PYTHON_INTERPRETER=$(python -c "import sys; print(sys.executable)")
          export PROJECT_HOME="$GITHUB_WORKSPACE"
          export SOLACE_CLOUD_API_TOKEN_ALL_PERMISSIONS="${{ secrets.SOLACE_CLOUD_API_TOKEN_ALL_PERMISSIONS }}"
          export SOLACE_CLOUD_API_TOKEN_RESTRICTED_PERMISSIONS="${{ secrets.SOLACE_CLOUD_API_TOKEN_RESTRICTED_PERMISSIONS }}"
          export LOG_DIR=${TEST_TEST_RUNNER_LOG_DIR}
          ./${TEST_TEST_RUNNER_SCRIPT}

      - name: Archive logs
        if: always()
        env:
          RUNNER_ASSET_DIR: ./${{ env.TEST_RUNNER_LOGS_DIR }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TEST_TEST_RUNNER_LOGS_NAME }}
          path: ${{ env.RUNNER_ASSET_DIR }}
          if-no-files-found: error

###
# The End.
