# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke, <ricardo.gomez-ulmke@solace.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

name: upload release to galaxy
on:
  # for testing
  workflow_dispatch:

  release:
    types: [created]

env:
  TEST_ANSIBLE_SOLACE_COLLECTION_DIR: "src/ansible_collections/solace/pubsub_plus"

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Check Auth
        if: github.event_name == 'workflow_dispatch' && github.actor != 'ricardojosegomezulmke'
        run: |
          echo "not authorized"
          echo '::set-output name=IS_AUTHORIZED::false'
        id: auth
      - name: Cancel Workflow
        if: ${{ always() && steps.auth.outputs.IS_AUTHORIZED == 'false' }}
        uses: andymckay/cancel-action@0.2

      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install ansible and collection dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install docs make dependencies
        run: |
          pip install -r devel/devel.requirements.txt

      - name:     


      # - name: Build and publish collection
      #   env:
      #     ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
      #   run: |
      #     cd ${TEST_ANSIBLE_SOLACE_COLLECTION_DIR}
      #     ansible-galaxy collection build .
      #     ansible-galaxy collection publish *.tar.gz --api-key $ANSIBLE_GALAXY_TOKEN


###
# The End.
